name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build multi-arch docker images
      run: make buildx

    - name: Build regular docker images
      run: make build

    - name: Test docker images
      run: make test
